service: lambda-monitor

package:
  exclude:
    - test/**
    - coverage/**
    - config/**

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage}
  region: us-east-1
  memorySize: 256
  timeout: 10
  versionFunctions: false
  environment:
    ROLLBAR_ACCESS_TOKEN: ${file(config/${self:provider.stage}.yml):ROLLBAR_ACCESS_TOKEN}
    LOGGLY_TOKEN: ${file(config/${self:provider.stage}.yml):LOGGLY_TOKEN}
    LOGZ_TOKEN: ${file(config/${self:provider.stage}.yml):LOGZ_TOKEN}
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lambda:ListFunctions"
        - "lambda:ListTags"
        - "logs:PutRetentionPolicy"
        - "logs:PutSubscriptionFilter"
      Resource:
        - "*"

functions:
  process-logs:
    handler: lib/handler.processLogs
    description: Processor for Lambda CloudWatch Streams
    tags:
      MONITOR: "1"
      MONITORED: "0"

  subscribe:
    handler: lib/handler.subscribe
    description: Subscribe Processor to Lambda CloudWatch Streams
    events:
      - schedule: rate(1 hour)

  set-retention:
    handler: lib/handler.setRetention
    description: Update Retention for Lambda CloudWatch Streams
    events:
      - schedule: rate(1 hour)

resources:
  Resources:
    LambdaInvokePermission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:InvokeFunction
        FunctionName: ${self:service}-${self:provider.stage}-process-logs
        Principal: logs.${self:provider.region}.amazonaws.com
