service: lambda-monitor

package:
  exclude:
    - test/**
    - coverage/**
    - .vars/**

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  memorySize: 256
  timeout: 10
  versionFunctions: false
  stackTags:
    MONITORED: "false"
  environment:
    ${file(.vars/${opt:stage, self:provider.stage}.yml)}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lambda:GetFunction"
      Resource:
        - arn:aws:lambda:${self:provider.region}:*:function:*

functions:
  process-logs:
    handler: lib/handler.processLogs
    description: Analyse and Process Lambda CloudWatch Logs
