service: lambda-monitor

package:
  exclude:
    - test/**
    - coverage/**
    - .vars/**

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage}
  region: us-east-1
  memorySize: 256
  timeout: 10
  versionFunctions: false
  stackTags:
    MONITORED: "false"
  environment:
    ROLLBAR_ACCESS_TOKEN: ${file(.vars/${self:provider.stage}.yml):ROLLBAR_ACCESS_TOKEN}
    LOGGLY_TOKEN: ${file(.vars/${self:provider.stage}.yml):LOGGLY_TOKEN}
    LOGZ_TOKEN: ${file(.vars/${self:provider.stage}.yml):LOGZ_TOKEN}
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lambda:ListFunctions"
        - "lambda:ListTags"
        - "logs:putRetentionPolicy"
      Resource:
        - "*"

functions:
  process-logs:
    handler: lib/handler.processLogs
    description: Processor for Lambda CloudWatch Streams

  subscribe:
    handler: lib/handler.subscribe
    description: Subscribe Processor to Lambda CloudWatch Streams
    events:
      - schedule: rate(1 hour)

  set-retention:
    handler: lib/handler.setRetention
    description: Update Retention for Lambda CloudWatch Streams
    events:
      - schedule: rate(1 hour)
